name:                fun-servant
version:             0.1.0.0
github:              "githubuser/fun-servant"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fun-servant#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- stm
- servant-auth-server
- containers
- text
- mtl
- bytestring
- QuickCheck
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- rio

library:
  source-dirs: src

executables:
  fun-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - fun-servant

default-extensions:
  - NoImplicitPrelude

tests:
  fun-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - fun-servant
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
